USE SalesOrderManagementDb;
GO

CREATE TABLE COM_CUSTOMER (
    COM_CUSTOMER_ID INT NOT NULL,
    CUSTOMER_NAME VARCHAR(100) NOT NULL,
    CONSTRAINT PK_COM_CUSTOMER PRIMARY KEY (COM_CUSTOMER_ID)
);
GO

CREATE TABLE SALES_SO (
    SALES_SO_ID INT NOT NULL,
    SO_NO VARCHAR(20) NOT NULL,
    ORDER_DATE DATETIME NOT NULL,
    COM_CUSTOMER_ID INT NOT NULL,
    ADDRESS VARCHAR(500) NULL,
    CONSTRAINT PK_SALES_SO PRIMARY KEY (SALES_SO_ID),
    CONSTRAINT FK_SALES_SO_CUSTOMER
        FOREIGN KEY (COM_CUSTOMER_ID)
        REFERENCES COM_CUSTOMER(COM_CUSTOMER_ID)
);
GO

CREATE TABLE SALES_SO_LITEM (
    SALES_SO_LITEM_ID INT NOT NULL,
    SALES_SO_ID INT NOT NULL,
    ITEM_NAME VARCHAR(100) NOT NULL,
    QUANTITY INT NOT NULL,
    PRICE FLOAT NOT NULL,
    CONSTRAINT PK_SALES_SO_LITEM PRIMARY KEY (SALES_SO_LITEM_ID),
    CONSTRAINT FK_SALES_SO_LITEM_SO
        FOREIGN KEY (SALES_SO_ID)
        REFERENCES SALES_SO(SALES_SO_ID)
);
GO

INSERT INTO COM_CUSTOMER
    (COM_CUSTOMER_ID, CUSTOMER_NAME)
VALUES
    (1, 'PT Maju Bersama'),
    (2, 'CV Sejahtera Abadi'),
    (3, 'PT Karya Utama');
GO